### ISSUE TITLE
[Question] What is klipper?

### ISSUE THREAD

**Issue by brandonkal** [rancher/klipper-helm#8]
I see this image is used by the helm-controller. But what is klipper?

**Comment by ibuildthecloud** [comment]
So..... Before k3s was released and we did substantial press around it there were people that wanted it to have a "less stupid name."  For a short time it was going to be named klipper and it was during this short window that we developed both the helm-controller and service lb functionality in k3s.  So this and https://github.com/rancher/klipper-lb got the klipper moniker.  I eventually put my foot down and decided to stick with the "stupid" k3s name.  As a side effect this repo never got renamed.  The helm-controller used to be an embedded component in k3s put we pulled it out to be standalone. So now the helm-controller references this image.

We will eventually rename this but it's mostly just been that we have so much work on k3s that this has been low priority.
